/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controle.de.qualidade;

import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.JLabel;

/**
 *
 * @author Bruno
 */
public class UIAvVenda extends javax.swing.JFrame {

	/**
	 * Creates new form AvVenda
	 *
	 * @param c
	 * @param v
	 */
	public UIAvVenda(Cliente c, Venda v) {
		this.c = c;
		this.v = v;
		System.out.println(v.toString());
		initComponents();
		jTextArea2.setEditable(false);
		jTextArea2.setText(v.getDescr_venda().replaceAll("@", "\n"));

	}

	private void updateCount() {
		remaningLabel.setText((500 - doc.getLength()) + " characters remaining");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelTitulo.setText("Avaliação da Oficina");
        jPanel1.add(labelTitulo);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição"));

        jTextArea2.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
        jTextArea2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 59, 400, 160));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Nota*"));
        jPanel4.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setText("0");
        jPanel2.add(jLabel1);

        jSlider1.setPaintLabels(true);
        jSlider1.setToolTipText("Dê sua nota ao serviço feito pela oficina.");
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jPanel2.add(jSlider1);

        jLabel4.setText("10");
        jPanel2.add(jLabel4);

        jPanel4.add(jPanel2);

        jLabel5.setText("5.0");
        jPanel5.add(jLabel5);

        jPanel4.add(jPanel5);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 400, 80));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Sugestões"));

        jTextArea3.setColumns(20);
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setToolTipText("Deixe suas sugetões, críticas e elogios. Sua opinião é muito importante.");
        jTextArea3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea3KeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 400, 200));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 400, 40));

        setSize(new java.awt.Dimension(417, 573));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
		nota = (float) jSlider1.getValue() / 10;
		jLabel5.setText(String.valueOf(nota));
    }//GEN-LAST:event_jSlider1StateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		try {
			new UICMenu(c).setVisible(true);
		} catch (SQLException ex) {
			Logger.getLogger(UIAvOficina.class.getName()).log(Level.SEVERE, null, ex);
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
			Logger.getLogger(UIAvVenda.class.getName()).log(Level.SEVERE, null, ex);
		}
		this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
		String data = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
		try {
			avaliacao = new AvVenda(v.getCpf_cliente(), v.getCpf_funcionario(), data, v.getData_venda(), jSlider1.getValue()/10, jTextArea3.getText());
			new UIAvSucesso(c).setVisible(true);
			this.dispose();
		} catch (SQLException ex) {
			Logger.getLogger(UIAvVenda.class.getName()).log(Level.SEVERE, null, ex);
			new UIAvNaoSucesso(c).setVisible(true);
			this.dispose();
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
			Logger.getLogger(UIAvVenda.class.getName()).log(Level.SEVERE, null, ex);
		}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextArea3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea3KeyReleased
		String txt;
		txt = jTextArea3.getText();
		if (txt.length() > 500) {
			jTextArea3.setText(txt.substring(0, 500));
		}
    }//GEN-LAST:event_jTextArea3KeyReleased

    private void jTextArea3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea3KeyPressed
		String txt;
		txt = jTextArea3.getText();
		if (txt.length() > 500) {
			jTextArea3.setText(txt.substring(0, 500));
		}
    }//GEN-LAST:event_jTextArea3KeyPressed

    private void jTextArea3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea3KeyTyped
		String txt;
		txt = jTextArea3.getText();
		if(txt.length()>500){
			jTextArea3.setText(txt.substring(0,500));
		}
    }//GEN-LAST:event_jTextArea3KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
	private Cliente c;
	private Venda v;
	private AvVenda avaliacao;
	private float nota;
	private DefaultStyledDocument doc;
	private JLabel remaningLabel = new JLabel();
}
