/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controle.de.qualidade;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Bruno
 */
public class UILogin extends javax.swing.JFrame {

	/**
	 * Creates new form TelaInicial
	 */
	public UILogin() {
		initComponents();
//		jTextField1.getCaret().setBlinkRate(0);
//		jTextField1.setCaretColor(Color.white);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter CPF = new javax.swing.text.MaskFormatter("###.###.###-##");
            CPF.setPlaceholderCharacter('_');
            jTextField1 = new javax.swing.JFormattedTextField(CPF);
        }catch(Exception e){
        }
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        warningLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de controle de qualidade");
        getContentPane().setLayout(new java.awt.GridLayout(3, 0));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Faça seu Login:");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Digite seu CPF:");
        jPanel2.add(jLabel2);

        jTextField1.setColumns(11);
        jTextField1.setToolTipText("Digite seu CPF com apenas números");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField1);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        getContentPane().add(jPanel2);

        warningLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        warningLabel.setForeground(new java.awt.Color(204, 0, 0));
        jPanel3.add(warningLabel);

        getContentPane().add(jPanel3);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		try {
			this.login();
		} catch (SQLException ex) {
			warningLabel.setText("Erro: Falha na conexão com o BD");
			Logger.getLogger(UILogin.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        String temp = jTextField1.getText().replaceAll("[^0-9]", "");
        jTextField1.setText(temp);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                this.login();
            } catch (SQLException ex) {
                warningLabel.setText("Erro: Falha na conexão com o BD");
                Logger.getLogger(UILogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTextField1KeyPressed


	private void login() throws SQLException {
		Cliente c;
		Funcionario f;
		String cpf;
		int tam;

		cpf = jTextField1.getText();
		cpf = cpf.replaceAll("[^0-9]", "");
		//System.out.println(cpf);
		tam = cpf.length();

		if ((tam != 11 && !cpf.matches("[0-9]+")) || tam == 0) {
			warningLabel.setText("<html>CPF Inválido!!! <br />O CPF deve conter 11 dígitos.</html>");
		} else if (tam != 11) {
			warningLabel.setText("<html>CPF Inválido!!! <br />O CPF deve conter 11 dígitos.</html>");
		} else if (!cpf.matches("[0-9]+")) {
			warningLabel.setText("<html>CPF Inválido!!! <br />O CPF deve conter apenas números.</html>");
		} else {
			c = new Cliente();
			f = new Funcionario();
			if (c.buscarCliente(cpf)) {
				new UICMenu(c).setVisible(true);
				this.dispose();
			} else if (f.buscarFuncionario(cpf)) {
				new UIFMenu(f).setVisible(true);
				this.dispose();
			} else {
				warningLabel.setText("CPF não cadastrado!");
			}
		}
	}
	/**
	 * @param args the command line arguments
	 */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
